### PR TITLE
Fixing some CI stuff

### PR DESCRIPTION
**Pull request by Clonkk**
Example of page live : https://clonkk.github.io/ngron/ 

If you don't like Nim default documentation, you can generate a very pretty docs with : https://github.com/pietroppeter/nimibook that I highly recommend (@HugoGranstrom and @pietroppeter are doing fantastic work) but it's a bit more work to setup.

Note that to make it work you have to enable github page from a workflow and because Github UI does not allow you to use an existing workflow you have to click on `create workflow` and duplicate `docdeploy.yml` (or delete docdeploy.yml before hand and re-created it from their UI : it's UI bug they have to fix)

I added a CI action to publish compiled binaries for OSX and Linux whenever a release is created so that's it's easy to manage :) : It's easier than recommending people to compile from Nim/nimble. I created a dummy release on my fork you can check it out

### CODE REVIEW

**Comment by Clonkk** [comment]
From the comment, it seems that the .github page might be ported directly to your repo

**Comment by virizar** [comment]
All these looks great :) 

One thing I would suggest is to build the executable with release flags for performance and stripping debug symbols, I believe `nimble build` builds in debug by default

I normally build with `nimble build -d:release --stacktrace:off -d:danger`, not really sure about the validity of the other flags, I recall reading about these some while ago regarding performance.

**Comment by virizar** [comment]
> Example of page live : https://clonkk.github.io/ngron/
> 
> If you don't like Nim default documentation, you can generate a very pretty docs with : https://github.com/pietroppeter/nimibook that I highly recommend (@[HugoGrantstrom](https://github.com/HugoGranstrom) and @[pietroppeter](https://github.com/pietroppeter/nimibook) are doing fantastic work) but it's a bit more work to setup.
> 
> Note that to make it work you have to enable github page from a workflow and because Github UI does not allow you to use an existing workflow you have to click on `create workflow` and duplicate `docdeploy.yml` (or delete docdeploy.yml before hand and re-created it from their UI : it's UI bug they have to fix)
> 
> I added a CI action to publish compiled binaries for OSX and Linux whenever a release is created so that's it's easy to manage :) : It's easier than recommending people to compile from Nim/nimble. I created a dummy release on my fork you can check it out

When I try to access your github page it returns 404 is that expected?

**Comment by Clonkk** [comment]
> When I try to access your github page it returns 404 is that expected?

It's not, but I think I know why, I'll fix it (just a missing index.html). EDIT: It's back online :) 

> nimble build -d:release --stacktrace:off -d:danger

Yup, I forgot the flag. Those are redundant though we only need danger or release here

You can see what the flag does here : https://github.com/nim-lang/Nim/blob/d72b848d1799191b4b5535336b3a708205374b31/config/nim.cfg#L72

As you can see release or danger already turn off stacktrace and danger imply release

**Pull request merged**
